version: "3"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=nabu
      - MONGODB_USERNAME=myuser
      - MONGODB_PASSWORD=mypass
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/bitnami/mongodb/data
  express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_USERNAME=me_user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=me_pass
    depends_on:
      - mongo
    restart: always